version: "3"

services:
  # Discord bot
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DDS-Bot-Dev
    environment:
      BOT_TOKEN: ${BOT_DEV_TOKEN}
      OWNER_ID: ${OWNER_ID}
    restart: unless-stopped