version: "3"

services:
  # Discord bot
  bot:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DDS-Bot-Dev
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    restart: unless-stopped