version: "3"

services:
  # Discord bot - production
  discord-bot:
    env_file: .env.production
    image: "ghcr.io/dutchdronesquad/dds-bot:latest"
    tty: true
    environment:
      BOT_TOKEN: ""
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1m